In [4]:
import numpy as np
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

In [9]:
python_list = [1, 2, 3]
python_list

[1, 2, 3]

In [10]:
np_list = np.array([1, 2, 3])
np_list

array([1, 2, 3])

In [11]:
python_list = [[1, 2, 3], [1, 2, 3], [1, 2, 3]]
python_list

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [12]:
np_list = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
np_list

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [13]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [14]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
array1 * array2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [16]:
array1 - array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
array1 / array2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
array3 = np.array([1, 2, 3])
array4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [19]:
array3 + array4

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [20]:
array3 * array4

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [21]:
array3 - array4

array([[ 0,  0,  0],
       [-3, -3, -3],
       [-6, -6, -6]])

In [22]:
array3 / array4

array([[1.        , 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ],
       [0.14285714, 0.25      , 0.33333333]])

In [23]:
array5 = np.array([1, 2, 3, 4])
array6 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [24]:
arra5 + array6

NameError: name 'arra5' is not defined

### IndexingとSlicing

In [25]:
ndarray = np.array(([1, 2], [3, 4], [5, 6]))
print(ndarray)

[[1 2]
 [3 4]
 [5 6]]


In [26]:
print(ndarray[1][0])
print(ndarray[1, 0])

3
3


In [27]:
array = np.array([1, 2, 3, 4, 5, 6, 7])
print(array[1:6])
print(array[1:6:2])

[2 3 4 5 6]
[2 4 6]


### [N:M:L]とするとL-1飛びでslicingできます．

In [28]:
ndarray = np.array([1, 2, 3])
print(ndarray)

[1 2 3]


In [33]:
np.arange(0, 5, 2)

array([0, 2, 4])

### np.arange(start, stop(, step))
### startからstopまでをstepおきに作成

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [36]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [81]:
np.arange(1, 2, 20)

array([1])

In [83]:
np.arange(100, 200, 20)

array([100, 120, 140, 160, 180])

In [80]:
np.linspace(1, 2, 20)

array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

### np.linspace(start, stop, num=50)
### np.arange()がstepだったのに対し，np.linspace()は要素の数(num)を指定します．startからstopまでの値をnum等分した値がarrayで返されます．stepを指定したい時はnp.arange()で，stepはなんでもいいが特定の数だけほしいという場合はnp.linspace()を使いましょう．stopの値を含むことに注意しましょう．

In [45]:
ndarray = np.arange(0, 5)
ndarray_copy = ndarray.copy()
print("original array's id is {}".format(id(ndarray)))
print("copied array's id is {}".format(id(ndarray_copy)))

#changing original array
ndarray[:] = 100
print('original array:\n', ndarray)
print('copied array:\n', ndarray_copy)

original array's id is 4728582512
copied array's id is 4728626592
original array:
 [100 100 100 100 100]
copied array:
 [0 1 2 3 4]


In [43]:
def myfunc(n):
    print(id(n))

a = 'test'
print(id(a))
myfunc(a)

4556098032
4556098032


In [53]:
def add_world(hello):
    hello += ' world'
    return hello

In [72]:
h_str = 'hello'
h_list = ['h', 'e', 'l', 'l', 'o']
h_array = [ndarray]
output_str = add_world(h_str)
output_list = add_world(h_list)
output_array = add_world(h_array)

print('output_str: {}'.format(output_str))
print('outpur_list: {}'.format(output_list))
print('outpur_array: {}'.format(output_array))


print('h_str: {}'.format(h_str))
print('h_list: {}'.format(h_list))

output_str: hello world
outpur_list: ['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']
outpur_array: [array([0, 1, 2, 3, 4]), ' ', 'w', 'o', 'r', 'l', 'd']
h_str: hello
h_list: ['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']


In [78]:
def change_hundred(array):
    
    array[0] = 100
    return array

def change_hundred_copy(array):
    
    array_copy = array.copy()
    array_copy[0] = 100
    return array_copy

array_1 = np.arange(0, 4)
array_2 = np.arange(0, 4)

output_array = change_hundred(array_1)
output_array_copy = change_hundred_copy(array_2)

print('original array_1:\n', array_1)
print('original array_2:\n', array_2)

original array_1:
 [100   1   2   3]
original array_2:
 [0 1 2 3]


In [86]:
shape = (2, 3, 5)
zeros = np.zeros(shape)
print(zeros)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [94]:
shape = (2, 3, 5)
ones_array_1 = np.ones(shape)
ones_array_2 = np.ones(0)
ones_array_3 = np.ones(4)
ones_array_4 = np.ones(4, str)
ones_array_5 = np.ones(4, list)


print(ones_array_1)
print(ones_array_2)
print(ones_array_3)
print(ones_array_4)
print(ones_array_5)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[]
[1. 1. 1. 1.]
['1' '1' '1' '1']
[1 1 1 1]


In [95]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [97]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [104]:
random_float = np.random.rand()
random_1d = np.random.rand(3)
random_2d = np.random.rand(3, 4)

print('random_float: {}\n'.format(random_float))
print('random_1d: {}\n'.format(random_1d))
print('random_2d: {}\n'.format(random_2d))

random_float: 0.4445561691277998

random_1d: [0.14197593 0.09119996 0.50833608]

random_2d: [[0.02371564 0.37267115 0.00936001 0.76813128]
 [0.87092066 0.67081241 0.29320597 0.57474059]
 [0.4039348  0.28445985 0.4956279  0.79122696]]



In [107]:
random_float = np.random.randn()
random_1d = np.random.randn(3)
random_2d = np.random.randn(3, 4)

print('random_float: {}\n'.format(random_float))
print('random_1d: {}\n'.format(random_1d))
print('random_2d: {}\n'.format(random_2d))

random_float: 0.4808453862578638

random_1d: [0.05191936 1.22786779 0.43038419]

random_2d: [[-0.68111082 -2.75083478 -0.19166033  0.4792586 ]
 [-0.21835871  1.15659919 -0.90862682  0.09156841]
 [-1.37827444 -1.20382964 -2.01804177  0.98607667]]



In [108]:
np.random.randint(10, 50, size=(2, 4, 3))

array([[[32, 13, 14],
        [11, 24, 26],
        [38, 11, 38],
        [31, 36, 45]],

       [[28, 41, 26],
        [33, 30, 44],
        [16, 36, 24],
        [41, 26, 26]]])

In [117]:
np.random.randint(10, 50)

31

In [123]:
np.random.randint(10, 50, size=(5, 2))

array([[25, 29],
       [15, 45],
       [12, 33],
       [15, 26],
       [11, 42]])

In [124]:
np.random.randint(10, 50, size=(5, 2, 3, 4))

array([[[[45, 18, 24, 43],
         [16, 49, 32, 13],
         [29, 24, 44, 42]],

        [[41, 16, 27, 22],
         [24, 24, 33, 21],
         [39, 46, 44, 42]]],


       [[[18, 20, 10, 40],
         [48, 44, 14, 37],
         [27, 25, 34, 11]],

        [[11, 10, 20, 33],
         [31, 26, 33, 42],
         [38, 34, 49, 46]]],


       [[[13, 44, 27, 41],
         [40, 40, 25, 30],
         [10, 26, 45, 22]],

        [[26, 35, 35, 29],
         [33, 44, 19, 16],
         [12, 48, 38, 23]]],


       [[[17, 37, 21, 23],
         [23, 44, 41, 11],
         [38, 31, 13, 23]],

        [[18, 16, 23, 22],
         [43, 12, 41, 10],
         [12, 14, 14, 32]]],


       [[[22, 11, 48, 41],
         [27, 27, 41, 25],
         [23, 43, 16, 14]],

        [[44, 38, 45, 45],
         [43, 16, 17, 12],
         [21, 18, 25, 13]]]])

### array sizeは()内左から大きい次元要素を構成する。

In [125]:
array = np.arange(0, 10)
print('array:\n{}'.format(array))
new_shape = (2,5)
reshaped_array = array.reshape(new_shape)
print('reshaped array:\n{} '.format(reshaped_array))
print("reshaped array's is:\n{} ".format(reshaped_array.shape)
print('original array is NOT changed:\n{} '.format(array))

array:
[0 1 2 3 4 5 6 7 8 9]
reshaped array:
[[0 1 2 3 4]
 [5 6 7 8 9]] 
reshaped array's is:
(2, 5) 
original array is NOT changed:
[0 1 2 3 4 5 6 7 8 9] 


### 要素の統計量を求める

In [138]:
normal_dist_mat = np.random.randn(5, 5)
print(normal_dist_mat)

[[-0.9606696  -0.48527364  0.76699555 -0.68894958 -0.21955458]
 [-0.59437136  1.54851914  0.0594528  -0.52617463  0.92606698]
 [-1.18213089 -0.60921807  1.85708625  0.30300804  1.27879178]
 [-0.98124631  0.31927197  0.38579873 -1.29155926  0.37956873]
 [-0.1617428  -0.81124379  1.26002191  1.41211518  1.14888685]]


In [156]:
print('max is:\naaa')
print(normal_dist_mat.max())
print(np.max(normal_dist_mat))

max is:
aaa
1.857086245784847
1.857086245784847


In [140]:
#argmax
print('argmax is')
print(normal_dist_mat.argmax())

argmax is
12


In [141]:
normal_dist_mat.flatten()[9]

0.9260669764871232

In [150]:
print(normal_dist_mat)
print(normal_dist_mat.argmax())
print(normal_dist_mat.flatten()[normal_dist_mat.argmax()])
print(normal_dist_mat.flatten()[2])

[[-0.9606696  -0.48527364  0.76699555 -0.68894958 -0.21955458]
 [-0.59437136  1.54851914  0.0594528  -0.52617463  0.92606698]
 [-1.18213089 -0.60921807  1.85708625  0.30300804  1.27879178]
 [-0.98124631  0.31927197  0.38579873 -1.29155926  0.37956873]
 [-0.1617428  -0.81124379  1.26002191  1.41211518  1.14888685]]
12
1.857086245784847
0.7669955509459917


In [152]:
print('min is')
print(normal_dist_mat.min())
print('argmin is')
print(normal_dist_mat.argmin())

min is
-1.2915592597698151
argmin is
18


In [153]:
print('mean is')
print(normal_dist_mat.mean())

mean is
0.12533797582552192


In [154]:
print('median is')
print(np.median(normal_dist_mat))

median is
0.0594528031519188


In [155]:
print('standard deviation is')
print(normal_dist_mat.std())

standard deviation is
0.9235191230380596


In [159]:
print(normal_dist_mat)
print('axis=0> {}'.format(normal_dist_mat.max(axis=0)))
print('axis=0< {}'.format(normal_dist_mat.min(axis=0)))
print('axis=1> {}'.format(normal_dist_mat.max(axis=1)))
print('axis=1< {}'.format(normal_dist_mat.min(axis=1)))
normal_dist_mat.min(axis=1)

[[-0.9606696  -0.48527364  0.76699555 -0.68894958 -0.21955458]
 [-0.59437136  1.54851914  0.0594528  -0.52617463  0.92606698]
 [-1.18213089 -0.60921807  1.85708625  0.30300804  1.27879178]
 [-0.98124631  0.31927197  0.38579873 -1.29155926  0.37956873]
 [-0.1617428  -0.81124379  1.26002191  1.41211518  1.14888685]]
axis=0> [-0.1617428   1.54851914  1.85708625  1.41211518  1.27879178]
axis=0< [-1.18213089 -0.81124379  0.0594528  -1.29155926 -0.21955458]
axis=1> [0.76699555 1.54851914 1.85708625 0.38579873 1.41211518]
axis=1< [-0.9606696  -0.59437136 -1.18213089 -1.29155926 -0.81124379]


array([-0.9606696 , -0.59437136, -1.18213089, -1.29155926, -0.81124379])

### また，特定の行，列での統計量を求めたい場合は引数axisを指定します．axis=0を指定すると各列の統計量，axis=1を指定すると各行の統計量を返します．このaxisの使い方は重要です．覚えておきましょう．
### >上記の例では例えば、axis=0>だと各列の最大値が帰ってきている

In [161]:
def axis0():
    return normal_dist_mat.max(axis=0)

In [162]:
axis0()

array([-0.1617428 ,  1.54851914,  1.85708625,  1.41211518,  1.27879178])